name: Run code linters and doc style checks.

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.4"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Verife code security
      run: bandit -r ./expliot_finder
      
    - name: Check docstrings style
      run: pydocstyle ./expliot_finder
    
    - name: Lint Python code
      run: |
        flake8 ./expliot_finder
        pylint --fail-under=9 ./expliot_finder
    
    - name: Verife static typing
      run: |
        mypy ./expliot_finder
